# -*- coding: utf-8 -*-
"""day_prior_covid19_symptoms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-uvoOO3qooAJ6tiIVjWDPQFai1KyMnx6
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tableone

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

# %load_ext google.colab.data_table

# Commented out IPython magic to ensure Python compatibility.
# change this to change the right project
# %env GOOGLE_CLOUD_PROJECT = sccm-datathon-2023-participant

# Commented out IPython magic to ensure Python compatibility.
# # example MIMIC-IV table 1 code here
# %%bigquery VIRUS_demographics --project sccm-datathon-2023-participant
# SELECT * FROM `sccm-discovery.VIRUS.coredata1_2` adm

VIRUS_demographic

VIRUS_demographics['sex'] = VIRUS_demographics['sex'].replace(1.0, 'Male')
VIRUS_demographics['sex'] = VIRUS_demographics['sex'].replace(2.0, 'Female')
VIRUS_demographics['sex'] = VIRUS_demographics['sex'].replace(3.0, 'Intersex')
VIRUS_demographics['sex'] = VIRUS_demographics['sex'].replace(4.0, 'Transgender')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(1.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(2.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(3.0, 'Black')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(4.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(5.0, 'White')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(6.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(7.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(8.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(9.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(10.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(11.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(12.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(12.0, 'Other')

VIRUS_demographics['ethnic_group'] = VIRUS_demographics['ethnic_group'].replace(1.0, 'Hispanic')
VIRUS_demographics['ethnic_group'] = VIRUS_demographics['ethnic_group'].replace(0.0, 'Non-Hispanic')
VIRUS_demographics['ethnic_group'] = VIRUS_demographics['ethnic_group'].replace(2.0, 'Non-Hispanic')
VIRUS_demographics['ethnic_group'] = VIRUS_demographics['ethnic_group'].replace(3.0, 'Non-Hispanic')

VIRUS_demographics=pd.DataFrame(VIRUS_demographics)

import pandas as pd
import matplotlib.pyplot as plt



# Create a box plot
plt.figure(figsize=(8, 6))
plt.boxplot(VIRUS_demographics['days_prior_covid_testing'].dropna())
#also day_prior_covid19_symptoms
plt.xlabel('Box Plot for day_prior_covid19_symptoms')
plt.title('Days')
plt.ylim(-10, 20)
plt.show()

VIRUS_demographics['days_prior_covid_testing'].plot.kde()

# Set plot labels and title
plt.xlabel('Values')
plt.ylabel('Density')
plt.title('Kernel Density Estimation (KDE) Plot')

# Commented out IPython magic to ensure Python compatibility.
# 
# 
# %%bigquery VIRUS_demographics --project sccm-datathon-2023-participant
# SELECT * FROM `sccm-discovery.VIRUS.coredata1_2` adm

cols=['sex','bmi_value','WHO_Region','race','age','ethnic_group','day_prior_covid19_symptoms','days_prior_covid_testing','quarter_patient_adm']

VIRUS_demographics=pd.DataFrame(VIRUS_demographics)

newDF=VIRUS_demographics[cols]

newDF=newDF[newDF['days_prior_covid_testing']>0]

newDF=newDF[newDF['days_prior_covid_testing']<15]

newDF=newDF[newDF['day_prior_covid19_symptoms']>0]
newDF=newDF[newDF['day_prior_covid19_symptoms']<15]



from google.colab import files

csv_filename = 'output.csv'
newDF.to_csv(csv_filename, index=False)
files.download(csv_filename)

newDF['days_prior_covid_testing'].plot.kde()

# Set plot labels and title
plt.xlabel('days_prior_covid_testing')
plt.ylabel('Density')
plt.title('Kernel Density Estimation (KDE) Plot')
plt.savefig('kde.png',dpi=300)

from google.colab import files

# Download the PNG file
files.download('kde.png')

df=tableone.tableone(
    VIRUS_demographics,
    columns = [
        'sex',
        'bmi_value',
        'WHO_Region',
        'race',
        'age',
        'ethnic_group',
        ],
    categorical = [
        'sex',
        'race',
        'WHO_Region',
        'ethnic_group',

        ],
    groupby=[
        'day_prior_covid19_symptoms', #
        ]
)

df

def downloadTable(df,name):
  html_content = df.to_html()

# Save the HTML content to a file
  with open(name, "w") as f:
    f.write(html_content)

# Download the HTML file
  files.download(name)

downloadTable(df,"day_prior_covid19_symptoms.html")

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery virus_demographics  --project sccm-datathon-2023-participant
# 
# SELECT cd12.*
#   , cd7.hosp_status
# 
# FROM `sccm-discovery.VIRUS.coredata1_2` cd12
# LEFT JOIN `sccm-discovery.VIRUS.coredata7` cd7 on (
#   cd7.icu_id = cd12.icu_id
# 
# )
#

virus_demographics['sex'] = virus_demographics['sex'].replace(1.0, 'Male')
virus_demographics['sex'] = virus_demographics['sex'].replace(2.0, 'Female')
virus_demographics['sex'] = virus_demographics['sex'].replace(3.0, 'Intersex')
virus_demographics['sex'] = virus_demographics['sex'].replace(4.0, 'Transgender')
virus_demographics['race'] = virus_demographics['race'].replace(1.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(2.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(3.0, 'Black')
virus_demographics['race'] = virus_demographics['race'].replace(4.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(5.0, 'White')
virus_demographics['race'] = virus_demographics['race'].replace(6.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(7.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(8.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(9.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(10.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(11.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(12.0, 'Other')
virus_demographics['race'] = virus_demographics['race'].replace(12.0, 'Other')

virus_demographics['ethnic_group'] = virus_demographics['ethnic_group'].replace(1.0, 'Hispanic')
virus_demographics['ethnic_group'] = virus_demographics['ethnic_group'].replace(0.0, 'Non-Hispanic')
virus_demographics['ethnic_group'] = virus_demographics['ethnic_group'].replace(2.0, 'Non-Hispanic')
virus_demographics['ethnic_group'] = virus_demographics['ethnic_group'].replace(3.0, 'Non-Hispanic')
virus_demographics['hosp_status'] = virus_demographics['hosp_status'].replace(0.0, 'Alive')
virus_demographics['hosp_status'] = virus_demographics['hosp_status'].replace(1.0, 'Deceased')

df=tableone.tableone(
    virus_demographics,
    columns = [
        'age', 'sex',
        'bmi_value',
        'race',
        'ethnic_group',
        'hosp_status',
        ],
    categorical = [
        'sex',
        'race',
        'ethnic_group',
        'hosp_status',
        ],
    groupby =[

    ]

)
df

downloadTable(df,"day_prior_covid19_symptoms.html")