# -*- coding: utf-8 -*-
"""mortalityRegion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LC5speL9wpr7MQnINqr5HdLPcqM4vn-d
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tableone

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import pandas as pd
import tableone
from google.colab import files
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

# %load_ext google.colab.data_table

# Commented out IPython magic to ensure Python compatibility.
# change this to change the right project
# %env GOOGLE_CLOUD_PROJECT = sccm-datathon-2023-participant

# Commented out IPython magic to ensure Python compatibility.
# # example MIMIC-IV table 1 code here
# %%bigquery VIRUS_demographics --project sccm-datathon-2023-participant
# SELECT * FROM `sccm-discovery.VIRUS.coredata1_2` adm

VIRUS_demographics['sex'] = VIRUS_demographics['sex'].replace(1.0, 'Male')
VIRUS_demographics['sex'] = VIRUS_demographics['sex'].replace(2.0, 'Female')
VIRUS_demographics['sex'] = VIRUS_demographics['sex'].replace(3.0, 'Intersex')
VIRUS_demographics['sex'] = VIRUS_demographics['sex'].replace(4.0, 'Transgender')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(1.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(2.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(3.0, 'Black')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(4.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(5.0, 'White')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(6.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(7.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(8.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(9.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(10.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(11.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(12.0, 'Other')
VIRUS_demographics['race'] = VIRUS_demographics['race'].replace(12.0, 'Other')

VIRUS_demographics['ethnic_group'] = VIRUS_demographics['ethnic_group'].replace(1.0, 'Hispanic')
VIRUS_demographics['ethnic_group'] = VIRUS_demographics['ethnic_group'].replace(0.0, 'Non-Hispanic')
VIRUS_demographics['ethnic_group'] = VIRUS_demographics['ethnic_group'].replace(2.0, 'Non-Hispanic')
VIRUS_demographics['ethnic_group'] = VIRUS_demographics['ethnic_group'].replace(3.0, 'Non-Hispanic')

df=tableone.tableone(
    VIRUS_demographics,
    columns = [
        'sex',
        'bmi_value',
        'WHO_Region',
        'race',
        'age',
        'ethnic_group',
        ],
    categorical = [
        'sex',
        'race',
        'WHO_Region',
        'ethnic_group',
        ],
    groupby=[
        'hosp_status' #
        ]
)

def downloadTable(df,name):
  html_content = df.to_html()

# Save the HTML content to a file
  with open(name, "w") as f:
    f.write(html_content)

# Download the HTML file
  files.download(name)

downloadTable(df,"hosp_status")





#other syntax for SQL
#%%bigquery virus_demographics  --project sccm-datathon-2023-participant

#SELECT cd12.*
#  , cd7.hosp_status

#FROM `sccm-discovery.VIRUS.coredata1_2` cd12
#LEFT JOIN `sccm-discovery.VIRUS.coredata7` cd7 on (
#  cd7.icu_id = cd12.icu_id

#)

